export const QUESTION_REQUESTED = 'QUESTION_REQUESTED';
export const QUESTION_RECEIVED = 'QUESTION_RECEIVED';
export const QUESTION_FAILED = 'QUESTION_FAILED';
export const INC_CURRENT_INDEX = 'INC_CURRENT_INDEX';
export const UPDATE_STATUS_MAP = 'UPDATE_STATUS_MAP';
export const INIT_STATUS_MAP = 'INIT_STATUS_MAP';
export const UPDATE_SCORE = 'UPDATE_SCORE';
